### ISSUE TITLE
Please move the v1 tag to the latest releases

### ISSUE THREAD

**Issue by attachmentgenie** [mathze/workflow-dispatch-action#117]
**Describe the bug**
the v1 tag currently still points to the 1.2.0 releases instead of $latest (1.3.0)

**To Reproduce**
1. Go to https://github.com/mathze/workflow-dispatch-action/tags
2. compare git hashes for v1, v1.2.0 and v1.3.0

**Expected behavior**
v1 tag to point to same git hash as v1.3.0

**Comment by mathze** [comment]
Hi @attachmentgenie,

I know I've forgot something^^.
Done
