### ISSUE TITLE
Failing with an auth error when getting the workflow ID 

### ISSUE THREAD

**Issue by rybesh** [mathze/workflow-dispatch-action#124]
**Describe the bug**
Sometime in the past few months this action started [failing with an auth error when getting the remote workflow ID](https://github.com/periodo/periodo-client/actions/runs/9407442069) when being run via a push. My token has the relevant permissions (I’ve been using this action for a few years without issues). Here is the relevant section of the logs:

```
Run mathze/workflow-dispatch-action@v1.3.0
  with:
    owner: periodo
    repo: periodo-tests
    ref: master
    token: ***
    use-marker-step: true
    workflow-name: run-tests-on-branch.yml
    payload: { "client_branch": "dependabot/npm_and_yarn/terser-5.31.1" }
  
    fail-on-error: false
Reading inputs
  Got inputs: Inputs(owner=periodo, repo=periodo-tests, ref=master, workflowName=run-tests-on-branch.yml, payload={"client_branch":"dependabot/npm_and_yarn/terser-5.31.1"}, token=***, failOnError=false, useIdentifierStep=true, runId=null, triggerTimeout=1m, triggerInterval=1s, waitTimeout=10m, waitInterval=1s)
Using external_ref_id: 9407442069-dispatch-and-wait-74064932-a9b6-4b24-b181-292c22f17cdf
Going to trigger workflow run.
Error: Receiving workflow id results in error! Details: {"headers":{"server":"GitHub.com","date":"Thu, 06 Jun 2024 20:31:32 GMT","content-type":"application/json; charset=utf-8","content-length":"80","x-github-media-type":"github.v3; format=json","x-ratelimit-limit":"60","x-ratelimit-remaining":"59","x-ratelimit-reset":"1717709492","x-ratelimit-used":"1","x-ratelimit-resource":"core","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","access-control-allow-origin":"*","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-frame-options":"deny","x-content-type-options":"nosniff","x-xss-protection":"0","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","content-security-policy":"default-src 'none'","vary":"Accept-Encoding, Accept, X-Requested-With","x-github-request-id":"0C91:123323:7C0FF0:D7DC51:66621CA4"},"body":"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/rest\"}","status-code":401,"status-message":"Unauthorized"}
Error: Unable to receive workflow id! Details see log
```

Strangely, it still works when I [run it manually](https://github.com/periodo/periodo-client/actions/runs/9407538909) (via the Run Workflow button):

```
Run mathze/workflow-dispatch-action@v1.3.0
  with:
    owner: periodo
    repo: periodo-tests
    ref: master
    token: ***
    use-marker-step: true
    workflow-name: run-tests-on-branch.yml
    payload: { "client_branch": "dependabot/npm_and_yarn/terser-5.31.1" }
  
    fail-on-error: false
Reading inputs
  Got inputs: Inputs(owner=periodo, repo=periodo-tests, ref=master, workflowName=run-tests-on-branch.yml, payload={"client_branch":"dependabot/npm_and_yarn/terser-5.31.1"}, token=***, failOnError=false, useIdentifierStep=true, runId=null, triggerTimeout=1m, triggerInterval=1s, waitTimeout=10m, waitInterval=1s)
Using external_ref_id: 9407538909-dispatch-and-wait-b4a9c37e-3617-40b8-a3c6-4dccb0940b0c
Going to trigger workflow run.
Got workflow-id 27047721 for workflow run-tests-on-branch.yml
```

**Data/Screenshots**

Dispatching workflow:
https://github.com/periodo/periodo-client/blob/master/.github/workflows/run-end-to-end-tests.yml

Dispatched workflow:
https://github.com/periodo/periodo-tests/blob/master/.github/workflows/run-tests-on-branch.yml

**System (please complete the following information):**
- Runner-OS: ubuntu-22.04
- Action-Version: v1.3.0

**Comment by mathze** [comment]
Hi @rybesh,
can't reproduce it. Works fine on my site, so I assume something with your PAT, maybe it's expired?

**Comment by rybesh** [comment]
> I assume something with your PAT, maybe it's expired?

I also assumed that at first. But after generating a new PAT, running the action with a manual dispatch works, but running the action automatically on push fails. It is the same token being passed in both cases, but it one case getting the workflow ID works, and in the other it fails with an auth error. Very strange.

**Comment by mathze** [comment]
Hi @rybesh,

sry for the late reply. I've tried to reproduce the problem:
- with a workflow triggering another within same repo on push to a branch => ✅ 
- with a workflow triggering another within another repo on push to a branch => ✅
- repeated above with a push triggered by merging PR => ✅
I've also tried to find something in the docs that changed but to no avail.

Maybe it would be best to contact someone from GH-Support. Maybe they have more insight into what's going on there.

I will close this issue as it doesn't seem to be a problem in the action.

**Comment by rybesh** [comment]
@mathze Thank you for taking the time to investigate. I agree that this is probably a GH issue.

Would you mind checking one thing for me? Do you use a “personal access token (classic)” or a “fine-grained personal access token (beta)”? “Repo” access now means slightly different things depending on the PAT type, and so the documentation has become a bit ambiguous. I think I’ve been trying to use the fine-grained token which may be the problem.

**Comment by mathze** [comment]
I still use the classic PAT.
