### ISSUE TITLE
False Positive on Failure

### ISSUE THREAD

**Issue by djthornton1212** [mathze/workflow-dispatch-action#14]
**Describe the bug**
When using `'Trigger and wait' mode` failed workflow_dispatch return positive: `::set-output name=failed::false`

**To Reproduce**
1. Configure workflow-dispatch-action action:
> - name: Docker Dispatch
id: dispatch
uses: mathze/workflow-dispatch-action@develop
with:
  owner: company
  repo: github-actions
  token: ${{ steps.generator.outputs.token }}
  workflow-name: docker-deploy.yml
  ref: develop
  payload: ${{ steps.json.outputs.ARTIFACT_JSON }}
  trigger-interval: 10s
  use-marker-step: true
  fail-on-error: true
  wait-interval: 30s

> - name: Wait for Docker to complete
uses: mathze/workflow-dispatch-action@develop
with:
  owner: company
  repo: github-actions
  ref: develop
  token: ${{ steps.generator.outputs.token }}
  run-id: ${{ steps.dispatch.outputs.run-id }}
  wait-interval: 30s
  wait-timeout: 10m
  fail-on-error: true

3. Click on deploy/Docker Deploy -> Wait for Docker to complete
4. Scroll down to
> Going to wait until run 1930309649 completes
##[debug]Time passed since start: 296ms
::set-output name=failed::false
5. See error:
> 
![image](https://user-images.githubusercontent.com/99346713/156650412-e974e599-7870-4825-91f9-7946edd5a90e.png)

FALSE POSITIVE:
![image](https://user-images.githubusercontent.com/99346713/156651373-4b867178-078d-4805-8da8-fc158701fd22.png)

**Expected behavior**
I would expect the remote triggered job's failure to cause a failure on the calling job per the `fail-on-error` option being set to true
**Data/Screenshots**
See above

**System (please complete the following information):**
- Runner-OS: [ubuntu-latest]
- Action-Version: develop (after issue 7 | PR #8 merge)

**Additional context**
I've printed out a debug of the result after polling to see what was being returned. Here's what I see:
> ##[debug]result after executPolling: (true, WorkflowRun(id=1930261490, etag="702c12c89ec61ad07967e79e11c203507ce3d60b7bcb5d8c9be5a5be7c1e08b1", branch=develop, status=COMPLETED, conclusion=FAILURE, jobs=Jobs(url=https://api.github.com/repos/company/github-actions/actions/runs/1930261490/jobs), dateCreated=2022-03-03T20:29:37Z))

**Comment by djthornton1212** [comment]
Ahh, just re-read the doc & action.yml. I was thinking that the action would fail the running job itself. I see now that it returns the completed status and I need to fail myself.

Is this correct?

**Comment by mathze** [comment]
Correct, the fail-on-error is for certain errors within the action itself. E.g. if we didn't get the workflow run within the specified timeout or a technical error occurred triggering the workflow-dispatch event.
But I see, I can improve the documentation on that and maybe also the output :) so thank you very much for your feedback.

**Comment by mathze** [comment]
> Thanks.
> 
> Maybe I can move this to enhancement then? Would you be opposed to a completed workflow output? Something that says the conclusion of the job? I'm already working on how to get that, though you'd probably get it lightyears before I figure it out.
> 
> And thanks for the quick response.

:) Already created #15 for that. Hope this will match your idea. If not feel free to add a comment.
