### ISSUE TITLE
Expose status and conclusion of triggered workflow through output 

### ISSUE THREAD

**Issue by mathze** [mathze/workflow-dispatch-action#15]
Currently there is no convenient way to react on the status/conclusion of the triggered workflow except by querying the gh-api manually.
Because the actions wait part already have the required information it would be beneficial to expose this information to the using workflow.
This would make our workflows smarter and easier to understand.
(Inspired by #14)

**Comment by djthornton1212** [comment]
I see your already working on exposing the results, thank you and thanks for the mention in the fix.

**Comment by mathze** [comment]
May be incomplete but had to merge PR to get test workflows to develop (default-branch)

**Comment by mathze** [comment]
@djthornton1212 I think I'm done 😄 but a real life test would be welcome before creating a new release 😉

**Comment by djthornton1212** [comment]
I'll test it this weekend.

Thanks!

**Comment by djthornton1212** [comment]
Works like a charm. 

I tested the develop branch and it worked as expected. Thank you!
