### ISSUE TITLE
Node v12 -> v16

### ISSUE THREAD

**Issue by djthornton1212** [mathze/workflow-dispatch-action#55]
**Is your feature request related to a problem? Please describe.**
The workflow-dispatch-action is now behind in regards to its version of node. The action now causes the following warning messages during a workflow run:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mathze/workflow-dispatch-action, mathze/workflow-dispatch-action
```

**Describe the solution you'd like**
Upgrade to node v16.

**Describe alternatives you've considered**
N/A

***Pro's and Con's***
Pros: Warning go away and the action will continue to function correctly.
Cons: Warning messages will continue & the action may stop functioning correctly in the future.

**Additional context**
Screen shot:
![Screen Shot 2022-10-21 at 4 37 46 PM](https://user-images.githubusercontent.com/99346713/197292628-f9e63f77-2873-49e7-bfac-939de2087361.png)

**Comment by mathze** [comment]
Update is already in main-branch, but I want to wait with a release until dependencies also can be updated (refer to #56).
I hope it will least not too long 🤞, and you can tolerate the annoying warnings 🙏.

**Comment by mathze** [comment]
#56 is finally done and I'm going to release a new version
