### ISSUE TITLE
Pending status is not recognised

### ISSUE THREAD

**Issue by MattGrundy** [mathze/workflow-dispatch-action#98]
**Describe the bug**
When there's a concurrencly limit on the triggered workflow "pending" status is not recognised in RunStatus and causes the error `Cannot map unknown value 'pending' to RunStatus!`

**To Reproduce**
On the triggered workflow have a concurrency that limits you to one run at a time
Trigger so that 2 of the triggered workflows are running at the same time (so that one of the workflows are pending)

**Expected behavior**
We wait until the timeout or the triggered workflow has succeeded

**Comment by mathze** [comment]
Released with [v1.2.1](https://github.com/mathze/workflow-dispatch-action/releases/tag/v1.2.1)
